import type { Metadata } from "next";
import Emerald from "next/font/local";
import "./globals.css";


// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

const emerald = Emerald({
  src: "./emerald.otf",
})

export const metadata: Metadata = {
  title: "Gregory Liu",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body
        className={emerald.className}
      >
        {children}
      </body>
    </html>
  );
}
